language: haxe

# haxe versions : http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.2.1"
  - "3.3.0-rc.1"
  - development

matrix:
  allow_failures:
  - haxe: development
    
addons:
  apt:
    packages:
      # PHP
      - php5-cli
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386

install:
  - git clone --recursive https://github.com/DoclerLabs/hexUnit.git ./hexunit
  - git clone --recursive https://github.com/DoclerLabs/hexCore.git ./hexcore
  - git clone --recursive https://github.com/DoclerLabs/hexAnnotation.git ./hexannotation
  - git clone --recursive https://github.com/DoclerLabs/hexInject.git ./hexinject
  - export DISPLAY=:99.0;
  - export AUDIODEV=null;
  - haxe flash/install.hxml

script:
  - if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-php.hxml && php bin/index.php; fi
  - if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-neko.hxml && neko bin/MainMDVCTest.n; fi
  - haxe build-js.hxml && node bin/MainMDVCTest.js
  - if [ $TRAVIS_HAXE_VERSION != "3.2.1" ]; then haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/MainMDVCTest.swf; fi
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com
      - laurent@geturl.net
